export const questions = [
  'Are you compared to any celebrities? To whom?',
  'If you could become immortal, at what age would you stop aging and why?',
  'What fruits and vegetables do you like best?',
  'Do you think you would be comfortable living without your smartphone for 24 hours?',
  'If you were going to change your name, what would you call yourself?',
  'What emoji/sticker do you use most often?',
  'If you had a personal assistant, what would you delegate to him or her?',
  'If you could instantly learn a language (other than English), what would you choose?',
  'Would you choose to be the funniest or the smartest person in the room?',
  'Imagine they were making a movie based on your biography. What genre would it be and who would play you?',
  'What do you think are some of the most amazing scientific discoveries?',
  "The '60s, '70s, '80s, '90s: which decade do you like best and why?",
  "If you didn't work the job you have now, what would you be?",
  'What mode of transportation is better to get to work - a donkey or a elephant?',
  'Do you only drink diet water?',
  "What is the opposite of the word 'opposite'?",
  'If animals can talk, what kind of speech can be considered rude?',
  "Why do girls in pants look normal, but guys in skirts don't?",
  'Why is chocolate not considered a vegetable if it is made from cocoa beans?',
  'What color is a confused chameleon?',
  'Why are bagels made with holes in them?',
  'Why do cellophane bags always fall apart badly?',
  'Can you call a broken escalator a ladder?',
  'Have you ever chased an ice cream truck?',
  "What is the man's dance in front of the toilet called? ",
  'What is the complexity of the algorithm for screwing a light bulb by seven programmers?',
  'Have you been delivering pizza?',
  'Do you like to play poker for money or strip poker?',
  'Do you buy insurance in case your code crashes on the production floor?',
  'Do you keep a stash in cookies?',
  "How often do you say to your computer, 'Please...'?",
  'Have you been accused of trying to program before?',
  'Do you agree that an admin should have a beard, even if he or she is a woman? ',
  'If you could write a book that was guaranteed to be a bestseller, what would you write about?',
  'If you were guaranteed something (other than money), what would you choose?',
  'If you were on a reality show, which show would you choose and why?',
  'If you could go to Mars, would you go? Why yes, why no?',
  'If you could see a certain movie again for the first time, what would you choose and why?',
  'What is your favorite TV series and why?',
  'Who is your favorite fairy tale character? Would you like to be in his/her shoes?',
  "Let's be honest, how often do you work lying in bed?",
  "What's the best advice you've ever received?",
  'If you could be an animal, what would you be and why?',
  'Does a pregnant horse theoretically have two horsepower?',
  'How do you accurately determine your age if you suddenly forget?',
  'Why were you born this way and not out of plasticine?',
  "Why did they invent obscene words if you can't say them?",
  'What do mosquitoes bite for?',
  'What do you call Little Red Riding Hood if she takes off her red hat?',
  "When you're old, will I have to go to your job?",
  "If I'm afraid to get married alone. Will you come with me?",
  "If there's a lot of iron in an apple, will a magnet be magnetized to the apple?",
  'And when an elephant carries a log, does its trunk not tear?',
  'What for you is the most difficult thing about working remotely? And the easiest?',
  'How many cups of coffee/tea a day do you drink?',
  'What does your work outfit (outfit) look like for telecommuting?',
  "Do you wear Hawaiian shorts under a classic shirt because you can't see the bottom on a video call anyway?",
  'Tell us about your dream house/apartment.',
  "What's your favorite city/country from the ones you've managed to visit?",
  'What worthwhile movie or TV series have you watched lately?',
  'Would you rather run at 100 km/hour or fly at 10 km/hour?',
  'Imagine you are going on a voyage around the world. What would you name your ship and why?',
  'What is your favorite form of transportation?',
  'Do you like to drink caffeinated beverages (tea, coffee, cola) while you work?',
  'Tell some fun fact about yourself.',
  "What's your favorite thing you've bought this year?",
  'What game did you love as a child?',
  'Imagine you have a choice: stay on a desert island alone or with your worst enemy. Which would you choose and why?',
  'Imagine hosting your own late-night talk show. Who would you invite as your first guest?',
  'What is the strangest food you have ever eaten?',
  'Would you rather be able to fly or become invisible?',
  'If you had a superpower, which one and why?',
  'Would you rather be an Olympic gold medalist or an astronaut?',
  'If you could commit some crime that you could get away with, what would you do and why?',
  'Do you have a favorite tradition or holiday? What is it?',
  'Which of the books you have read do you think is the best and why?',
  'If you had to teach one discipline, what would it be?',
  'What 5 movies would you recommend I watch?',
  'What country would you like to visit?',
  'What makes you feel satisfied?',
  "When you're in a bad mood, do you prefer to be left alone or cheered up?",
  'What makes you smile even on your worst days?',
  'What qualities in your parents do you admire?',
  'Do you consider yourself an extrovert or an introvert?',
  'What would you like to change about yourself?',
  'Do you believe in second chances?',
  'What is your favorite book/movie and why is it memorable?',
  'When have you experienced your biggest adrenaline rush?',
  'What is the perfect vacation for you?',
  'How do you rate your sense of humor?',
  'Do people always get your jokes right?',
  'What is your favorite song?',
  'What did you want to be when you were a kid?',
  'Do you do the things you dreamed of when you were a kid?',
  'Where do you like to go most - movies, restaurants, clubs, or maybe the planetarium?',
  'Is there someone you can talk to about anything?',
  'What is your favorite food and why?',
  'If you could master one new hard skill in the near future, what would it be?',
  'Imagine that you are very rich and no longer need to work. What would you do?',
  'Who do you think is the best in the business world and why?',
  'What do I do if my toilet bowl dances?',
  'Why did I get drunk last night?',
  'How do I become a princess?',
  'How do I use my cell phone to call the afterlife?',
  'How many hamsters does it take to get a good coat?',
  'Why did God create woman?',
  'How do you open a can of kilek with two spoons and a slipper?',
  'An atheist - what kind of stone?',
  'Why did I open Google?',
  'How do I get a cat out of the microwave?',
  'How beautiful am I?',
  'How do I make an atomic bomb at home?',
  'Do penguins have knees?',
  'How do you use a stapler out of the box?',
  'What do you think of garden gnomes?',
  'How would you solve problems if you came from Mars?',
  'Why are manholes round?',
  'What wallpaper do you have on your phone/computer?',
  'Where do you work most often at home? At your desk? At the kitchen table? On the balcony? On the couch? In your favorite chair?',
  'If you could choose two famous people to have dinner with, who would you choose?',
  'Would you rather lose all your money or all your pictures?',
  'How do you think our calls could be improved?',
  'If you could bring back any fashion trend, what would it be?',
  'What fictional world or place would you like to visit?',
  'Would you rather give up your smartphone or computer?',
  'If you had to eat one meal for the rest of your life, what would it be?',
  'If you had to remove all but 3 apps from your smartphone, what would you keep and why?',
  'What is your favorite time of year and why?',
  'How serious are you about online dating?',
  "What's the most interesting thing around you right now?",
  'Is friendship between a guy and a girl possible?',
  'How would you describe your best friend?',
  "What's the craziest thing you've ever done?",
  'If a genie promised you 3 wishes right now, what would you wish for?',
  'Which parent are you closer to?',
  "What do you pay more attention to when you're socializing - your looks or your intelligence?",
  'What is your biggest mistake in life?',
  'Has it taught you anything?',
  'What movie or TV show best describes your week?',
  'What is the worst and best thing about being a man?',
  'How do you feel about long distance relationships?',
  'What is the worst message you accidentally sent to the wrong person?',
  'What was your favorite actor/actress as a child?',
  'What is your favorite time of day and why?',
  'If you could live in any country, where would you live?',
  'If you had a time machine, would you go back in time or into the future?',
  "What is the most unusual thing you've ever had to do?",
  'If you could talk to any character in a story/movie, who would you choose and why?',
  'What musical group or performer would you like to call to your party?',
  'If you could develop one new soft skill in the near future, what would it be?',
  'The zombie apocalypse is coming, assemble a team of three for yourself. Why did you choose these particular people?',
  'Are you a traveler or a homebody?',
  'What is your favorite magical or mythological animal?',
  'Are you more fond of cats or dogs?',
  'If aliens came to Earth tomorrow and invited you to fly away with them, would you agree?',
  'What do you consider to be the best professional literature?',
  'If you were an Olympic athlete, what sport would it be and why?',
  'What do you like to eat for breakfast?',
  'What did you want to be as a child?',
  'How do you stay productive and motivated while working remotely?',
  'Do you play any musical instruments? What kind of instruments?',
  'What would you do if you met your idol?',
  'How do you like to work more: at home or in the office? Why? Would you like to combine telecommuting and office work, and if so, how?',
  'Would you prefer to always be a little late or come a little earlier?',
  'Do you like to sing/dance?',
  'Would you rather live in the ocean or on the moon?',
  "Would you show us your 'remote' workplace?",
  'Do you like to communicate by correspondence or would you rather meet?',
  'Do you meet people easily?',
  'Would you go on a blind date?',
  'On social networks, do you friend everyone or selectively?',
  "What's more important - looks or intelligence, feelings or perspective?",
  'Do you prioritize your personal relationships or your career?',
  "What can't you give up under any circumstances?",
  "What do you do when you can't sleep?",
  'Do you prefer a quiet rest, a meeting with friends or a party at a club?',
  'How much time do you spend on social media?',
  'What life event makes you smile?',
  'Do you believe in fate or is everything in your hands?',
  'What influences your decisions - heart, intuition or mind?',
  'Do you live to the rhythm of drive or calm and predictability?',
  'How do you relax in stressful situations?',
  'Do you think there can only be friendship between a guy and a girl?',
  'Which celebrity would you like to meet?',
  'Where would you like to go with your lover?',
  'Does your horoscope data affect your relationship?',
  'What traits in a man are unbearable for you?',
  'Are you romantic?',
  'What is the most important thing in a relationship?',
  'Are you lovable or not?',
  "What compliment can't you forget?",
  'Are you willing to accept the man for who he is and compromise?',
  'Is jealousy love or mistrust?',
  'What kind of date do you think is ideal?',
  'What are the things a man does that are most valuable to you?',
  'Can you trust a man 100%?',
  'What lifestyle do you find most appealing?',
  'What do you plan for your life?',
  'Will you develop in your field or do you plan to learn something new?',
  'What book has shaken you up?',
  'Are you interested in the classics or modern?',
  'What countries would you like to visit?',
  'What movie are you ready to watch dozens of times?',
  "Do you learn from others' mistakes or from your own?",
  "What's your motto in life?",
  'Is your profession important only to you or to humanity as a whole as well?',
  'Are you a theorist or a practitioner?',
  'What are the three most important things in your life?',
  'Would you like to be famous and in what?',
  'What do you consider to be your most important achievement in life?',
  'What can you be most thankful for?',
  'What skill do you admire?',
  'Which person do you consider a hero?',
  'How important is freedom to you?',
  'If you had 2-3 hours more in the day, what would you spend it on?',
  'If you could write a book, what genre would you choose? Fantasy? Thriller? A novel? Historical fiction? Professional literature?',
  'Do you like to play sports? What kind of sports do you like the most?',
  "Do you have your own 'office' (separate workplace) at home?",
  "What do your mornings look like when you work from home and don't have to fancy up to go to the office?",
  'Coffee or tea?',
  'If you could eliminate one thing from your routine, what would it be and why?',
  'Are you a morning person or a night person? When is the most convenient time to work and do you get to organize a convenient schedule remotely?',
  'Tell us about your worst job.',
  'If you could switch places with anyone in the world, who would it be and why?',
  'Tell us about your worst/inappropriate outfit?',
  'Imagine that you could choose an unlimited supply of some product for life. What would you choose?',
  'If you could live in any country for a year, what would you choose and why? ',
  'How many languages do you know?',
  'What three words describe you?',
  'Have you ever gone to a concert?',
  'If you could change your name, which one would you choose?',
  'Who was your favorite teacher?',
  'What was your favorite subject in school?',
  'How do you spend your free time?',
  'Do you play computer games and what kind of games?',
  'Would you risk your life to save someone?',
  'If you had the opportunity to win an Olympic medal in any sport, what sport would it be?',
  'Do you like fast food?',
  'Would you ever want to be famous?',
  'Would you like to go to a foreign country alone?',
  'Who would you save if your house was on fire?',
  "What's the strangest gift you've ever received?",
  'If you were offered a role in a movie, would you rather play the villain or the hero?',
  'How do you see your perfect girlfriend?',
  'If you could teleport right now, what place would you transport to and why?',
  'If you were in a competition like Miss/Mr. World, what would you present in a talent contest?',
  'Do you want to be famous? In what field?',
  'If you could instantly become an expert in something, what would it be?',
  "What's your top tip for keeping yourself busy while working from home?",
  'Would you rather be a superhero or the best chef in the world?',
  'Would you rather live without heat and AC or social media?',
  'Which famous person in history would you like to be friends with and why?',
  'What food did you hate growing up? How do you feel about it now?',
  'Tell us about your worst haircut?',
  'What would you call your autobiography?',
  'What is your favorite dessert?',
  'What are your dreams?',
  "Would you rather live where it's always cold or always hot?",
  'Do you like to sing karaoke? What is your favorite song?',
  'Teleportation or flying?',
  'Do you have a pet?',
  'Which animal would you like to get and which one would you absolutely not?',
  'Are you an extrovert or an introvert?',
  'Who do you look like - your dad or your mom?',
  'Which of your relatives are closer to you and why?',
  'On what topics can you not communicate with your parents?',
  'Are you touchy?',
  'Do you love children?',
  'Do you have a dream home?',
  'What holidays do you celebrate as a family?',
  'Will you raise your children the same way you were raised or differently?',
  'What do you feel sorry to spend your money on?',
  'What would you call a perfect morning?',
  'What do you like to eat?',
  "What's your favorite food?",
  'What are you most afraid of?',
  'What would you spend a million on?',
  'What country would you like to live in?',
  "Do you have a 'bucket list' - a list of things to get done in life?",
  'What is the most important/interesting thing on it?',
]
